[package]
name = "bit_ops_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.5.1"
itertools = "0.12.1"
once_cell = "1.19.0"
rand = "0.8.5"
rayon = "1.10.0"

[[bench]]
name = "benchmark"
harness = false
